import type { KeywordDemandSnapshot } from '../types';

// Generated by scripts/keyword-intelligence.mjs — do not edit by hand.
export const keywordIntelligence = {
  "generatedAt": "2026-10-04T10:35:11.856Z",
  "methodology": {
    "description": "EzyJobs combines Google autocomplete ranking across multiple query prefixes, Google Trends Trending Now signals where a relevant trend exists, and live EzyJobs job supply. The demand score is directional and is not an official monthly search-volume number.",
    "searchSource": "Google Autocomplete",
    "trendSource": "Google Trends Trending Now",
    "jobSource": "EzyJobs live jobs snapshot"
  },
  "keywords": [
    {
      "keyword": "remote jobs",
      "normalized": "remote jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 100,
      "suggestionCount": 22,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 90,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs maryland",
      "normalized": "remote jobs maryland",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 81,
      "suggestionCount": 20,
      "sourceQueryCount": 2,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 65,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs near me",
      "normalized": "remote jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 53,
      "suggestionCount": 20,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 64,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs washington",
      "normalized": "remote jobs washington",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 73,
      "suggestionCount": 20,
      "sourceQueryCount": 2,
      "jobMatches": 8,
      "trendScore": 0,
      "demandScore": 61,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs no experience",
      "normalized": "remote jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote jobs for students",
        "remote jobs worldwide",
        "remote jobs europe",
        "remote jobs uk",
        "remote jobs france"
      ],
      "searchScore": 33,
      "suggestionCount": 10,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 53,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote part time jobs",
      "normalized": "remote part time jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 33,
      "suggestionCount": 11,
      "sourceQueryCount": 1,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 49,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote customer service jobs",
      "normalized": "remote customer service jobs",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 23,
      "suggestionCount": 14,
      "sourceQueryCount": 4,
      "jobMatches": 258,
      "trendScore": 0,
      "demandScore": 48,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data entry jobs",
      "normalized": "remote data entry jobs",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 19,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 44,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data analyst jobs",
      "normalized": "remote data analyst jobs",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 18,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 156,
      "trendScore": 0,
      "demandScore": 44,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data entry jobs maryland",
      "normalized": "remote data entry jobs maryland",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 16,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 43,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data entry jobs no experience",
      "normalized": "remote data entry jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 42,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "work from home jobs",
      "normalized": "work from home jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 13,
      "suggestionCount": 4,
      "sourceQueryCount": 4,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 42,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote software engineer jobs",
      "normalized": "remote software engineer jobs",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 235,
      "trendScore": 0,
      "demandScore": 41,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "work from home jobs alexandria va",
      "normalized": "work from home jobs alexandria va",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 13,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 262,
      "trendScore": 0,
      "demandScore": 40,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "part time remote jobs",
      "normalized": "part time remote jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 12,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 40,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data entry jobs virginia",
      "normalized": "remote data entry jobs virginia",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 10,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 40,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "work from home jobs near me",
      "normalized": "work from home jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 38,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data entry jobs near me",
      "normalized": "remote data entry jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 38,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "work from home jobs no experience",
      "normalized": "work from home jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 37,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote customer service jobs near me",
      "normalized": "remote customer service jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 258,
      "trendScore": 0,
      "demandScore": 37,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote customer service jobs part time",
      "normalized": "remote customer service jobs part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 5,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 258,
      "trendScore": 0,
      "demandScore": 36,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "وظائف عند شيوخ الإمارات",
      "normalized": "وظاي ف عند شيوخ الا مارات",
      "locale": "ar",
      "geo": "DZ",
      "intent": "jobs",
      "suggestions": [
        "وظائف عن بعد",
        "وظائف اونلاين",
        "وظائف من المنزل",
        "وظائف عن بعد في الجزائر",
        "وظائف اونلاين بدون خبرة"
      ],
      "searchScore": 33,
      "suggestionCount": 7,
      "sourceQueryCount": 2,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 35,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote customer service jobs hiring immediately",
      "normalized": "remote customer service jobs hiring immediately",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 10,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 74,
      "trendScore": 0,
      "demandScore": 34,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote customer service jobs maryland",
      "normalized": "remote customer service jobs maryland",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 13,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 55,
      "trendScore": 0,
      "demandScore": 33,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs uk",
      "normalized": "remote jobs uk",
      "locale": "en",
      "geo": "GB",
      "intent": "jobs",
      "suggestions": [
        "remote jobs europe",
        "remote jobs uk"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 33,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs entry level",
      "normalized": "remote jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "emploi à distance",
      "normalized": "emploi a distance",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi à distance"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "وظائف عن بعد للنساء",
      "normalized": "وظاي ف عن بعد للنساء",
      "locale": "ar",
      "geo": "DZ",
      "intent": "jobs",
      "suggestions": [
        "وظائف عن بعد",
        "وظائف اونلاين",
        "وظائف من المنزل",
        "وظائف عن بعد في الجزائر",
        "وظائف اونلاين بدون خبرة"
      ],
      "searchScore": 20,
      "suggestionCount": 9,
      "sourceQueryCount": 3,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote marketing jobs",
      "normalized": "remote marketing jobs",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 96,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote customer service jobs virginia",
      "normalized": "remote customer service jobs virginia",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 55,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "online jobs",
      "normalized": "online jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "online jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs entry level no experience",
      "normalized": "remote jobs entry level no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs europe",
      "normalized": "remote jobs europe",
      "locale": "en",
      "geo": "GB",
      "intent": "jobs",
      "suggestions": [
        "remote jobs europe",
        "remote jobs france"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "part time jobs alexandria va",
      "normalized": "part time jobs alexandria va",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 262,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "part time remote jobs alexandria va",
      "normalized": "part time remote jobs alexandria va",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 262,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data analyst jobs entry level",
      "normalized": "remote data analyst jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 156,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "work from home",
      "normalized": "work from home",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "part time jobs near me",
      "normalized": "part time jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "part time remote jobs near me",
      "normalized": "part time remote jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "العمل عن بعد",
      "normalized": "العمل عن بعد",
      "locale": "ar",
      "geo": "DZ",
      "intent": "jobs",
      "suggestions": [
        "العمل عن بعد"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote software engineer jobs entry level",
      "normalized": "remote software engineer jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 235,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "emploi",
      "normalized": "emploi",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi télétravail",
        "emploi en ligne",
        "emploi à distance"
      ],
      "searchScore": 13,
      "suggestionCount": 3,
      "sourceQueryCount": 1,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote marketing jobs maryland",
      "normalized": "remote marketing jobs maryland",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 96,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote marketing jobs pennsylvania",
      "normalized": "remote marketing jobs pennsylvania",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 96,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote marketing jobs entry level",
      "normalized": "remote marketing jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 96,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs entry level near me",
      "normalized": "remote jobs entry level near me",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs entry level part time",
      "normalized": "remote jobs entry level part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs worldwide",
      "normalized": "remote jobs worldwide",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs worldwide",
        "remote jobs france"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data analyst jobs no experience",
      "normalized": "remote data analyst jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 156,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote software engineer jobs reddit",
      "normalized": "remote software engineer jobs reddit",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 108,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data analyst jobs part time",
      "normalized": "remote data analyst jobs part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 5,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 156,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "emploi du temps",
      "normalized": "emploi du temps",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi télétravail",
        "emploi en ligne",
        "emploi à distance"
      ],
      "searchScore": 10,
      "suggestionCount": 3,
      "sourceQueryCount": 1,
      "jobMatches": 259,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "work from home part time jobs",
      "normalized": "work from home part time jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "part time remote jobs fredericksburg va",
      "normalized": "part time remote jobs fredericksburg va",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 262,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs entry level data entry",
      "normalized": "remote jobs entry level data entry",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data entry jobs part time",
      "normalized": "remote data entry jobs part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote data entry jobs"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 152,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote software engineer jobs usa",
      "normalized": "remote software engineer jobs usa",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 118,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote jobs no experience work from home",
      "normalized": "remote jobs no experience work from home",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote jobs no experience"
      ],
      "searchScore": 3,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "remote data analyst jobs near me",
      "normalized": "remote data analyst jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 3,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 156,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    },
    {
      "keyword": "وظائف اونلاين",
      "normalized": "وظاي ف اونلاين",
      "locale": "ar",
      "geo": "DZ",
      "intent": "jobs",
      "suggestions": [
        "وظائف عن بعد",
        "وظائف اونلاين",
        "وظائف من المنزل",
        "وظائف عن بعد في الجزائر",
        "وظائف اونلاين بدون خبرة"
      ],
      "searchScore": 20,
      "suggestionCount": 7,
      "sourceQueryCount": 2,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 28,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-04T10:35:11.856Z"
    }
  ],
  "inDemandRoles": [
    {
      "title": "Senior Account Executive",
      "count": 3,
      "remoteCount": 3,
      "directCount": 2
    },
    {
      "title": "Forward Deployed Engineer, Professional Services",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Principal Customer Engineer, Majors",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Strategic Account Executive - Public Sector ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Strategic Account Executive",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Senior Software Engineer, Billing Platform",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Associate Renewals Manager   ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Director of Product Management, Security",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Principal Product Manager, Security",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Intermediate-Senior Backend Engineer (Ruby), Plan: Spec-Driven Development",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Business Development Representative ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Candidate Experience Specialist, Contractor ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Security Engineer, Detection and Response",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Senior Web Compatibility Engineer",
      "count": 2,
      "remoteCount": 2,
      "directCount": 0
    },
    {
      "title": "Senior Privacy Engineer",
      "count": 2,
      "remoteCount": 2,
      "directCount": 0
    },
    {
      "title": "Senior Technical Program Manager, AI Platform",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Staff Software Engineer, AI Developer Tooling",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Staff Technical Program Manager, Machine Learning",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Regional Sales Director, National Security Group",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Integrated Marketing Manager, Hardware",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Total Rewards Business Partner, APAC",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Director of Events and Experiences",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": " APAC Vendor Lead, Ads",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "North America Vendor Lead, Ads",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Data Analytics Manager",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Global Workplace Business Operations Lead",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Dedicated Support Engineer - London",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Recruiting Operations Consultant",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Field Marketing Manager, Healthcare / SLED",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Senior Manager, Customer Engineering UKI ",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    }
  ],
  "errors": []
} as KeywordDemandSnapshot;
