import type { KeywordDemandSnapshot } from '../types';

// Generated by scripts/keyword-intelligence.mjs — do not edit by hand.
export const keywordIntelligence = {
  "generatedAt": "2026-10-07T11:05:15.044Z",
  "methodology": {
    "description": "EzyJobs combines Google autocomplete ranking across multiple query prefixes, Google Trends Trending Now signals where a relevant trend exists, and live EzyJobs job supply. The demand score is directional and is not an official monthly search-volume number.",
    "searchSource": "Google Autocomplete",
    "trendSource": "Google Trends Trending Now",
    "jobSource": "EzyJobs live jobs snapshot"
  },
  "keywords": [
    {
      "keyword": "remote jobs",
      "normalized": "remote jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 100,
      "suggestionCount": 22,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 90,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs near me",
      "normalized": "remote jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 63,
      "suggestionCount": 20,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 70,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs texas",
      "normalized": "remote jobs texas",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 81,
      "suggestionCount": 20,
      "sourceQueryCount": 2,
      "jobMatches": 1,
      "trendScore": 0,
      "demandScore": 65,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs california",
      "normalized": "remote jobs california",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 73,
      "suggestionCount": 20,
      "sourceQueryCount": 2,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 60,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs no experience",
      "normalized": "remote jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote jobs for students",
        "remote jobs worldwide",
        "remote jobs europe",
        "remote jobs uk",
        "remote jobs france"
      ],
      "searchScore": 31,
      "suggestionCount": 10,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 52,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote customer service jobs",
      "normalized": "remote customer service jobs",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 23,
      "suggestionCount": 14,
      "sourceQueryCount": 4,
      "jobMatches": 246,
      "trendScore": 0,
      "demandScore": 48,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs hiring",
      "normalized": "remote jobs hiring",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 39,
      "suggestionCount": 18,
      "sourceQueryCount": 2,
      "jobMatches": 30,
      "trendScore": 0,
      "demandScore": 46,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data entry jobs",
      "normalized": "remote data entry jobs",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 19,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 44,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data entry jobs no experience",
      "normalized": "remote data entry jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 16,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 43,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home jobs",
      "normalized": "work from home jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 4,
      "sourceQueryCount": 4,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 43,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data analyst jobs",
      "normalized": "remote data analyst jobs",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 158,
      "trendScore": 0,
      "demandScore": 42,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data entry jobs texas",
      "normalized": "remote data entry jobs texas",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 42,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote software engineer jobs",
      "normalized": "remote software engineer jobs",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 233,
      "trendScore": 0,
      "demandScore": 41,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data entry jobs california",
      "normalized": "remote data entry jobs california",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 12,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 41,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "part time remote jobs",
      "normalized": "part time remote jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 13,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 40,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote part time jobs",
      "normalized": "remote part time jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 14,
      "suggestionCount": 11,
      "sourceQueryCount": 1,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 39,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data entry jobs near me",
      "normalized": "remote data entry jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data entry jobs",
        "remote data analyst jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 4,
      "sourceQueryCount": 3,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 39,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home jobs near me",
      "normalized": "work from home jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 38,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote customer service jobs near me",
      "normalized": "remote customer service jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 246,
      "trendScore": 0,
      "demandScore": 38,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home jobs no experience",
      "normalized": "work from home jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 37,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home jobs remote",
      "normalized": "work from home jobs remote",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 5,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 36,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "وظائف عن بعد في الجزائر",
      "normalized": "وظاي ف عن بعد في الجزاي ر",
      "locale": "ar",
      "geo": "DZ",
      "intent": "jobs",
      "suggestions": [
        "وظائف عن بعد",
        "وظائف عن بعد في الجزائر"
      ],
      "searchScore": 23,
      "suggestionCount": 5,
      "sourceQueryCount": 3,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 33,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote customer service jobs hiring immediately",
      "normalized": "remote customer service jobs hiring immediately",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 11,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 61,
      "trendScore": 0,
      "demandScore": 33,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs uk",
      "normalized": "remote jobs uk",
      "locale": "en",
      "geo": "GB",
      "intent": "jobs",
      "suggestions": [
        "remote jobs europe",
        "remote jobs uk"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 33,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs work from home",
      "normalized": "remote jobs work from home",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote jobs for students",
        "remote jobs worldwide",
        "remote jobs europe",
        "remote jobs uk"
      ],
      "searchScore": 9,
      "suggestionCount": 7,
      "sourceQueryCount": 1,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs entry level",
      "normalized": "remote jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "part time jobs near me",
      "normalized": "part time jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "emploi à distance",
      "normalized": "emploi a distance",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi à distance"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "العمل عن بعد",
      "normalized": "العمل عن بعد",
      "locale": "ar",
      "geo": "DZ",
      "intent": "jobs",
      "suggestions": [
        "العمل عن بعد"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 32,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote nursing jobs",
      "normalized": "remote nursing jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs",
        "remote jobs no experience",
        "remote jobs entry level",
        "remote customer service jobs",
        "remote data entry jobs",
        "remote software engineer jobs",
        "remote data analyst jobs",
        "remote marketing jobs"
      ],
      "searchScore": 28,
      "suggestionCount": 11,
      "sourceQueryCount": 1,
      "jobMatches": 0,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "online jobs",
      "normalized": "online jobs",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "online jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs entry level no experience",
      "normalized": "remote jobs entry level no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "part time jobs",
      "normalized": "part time jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs worldwide",
      "normalized": "remote jobs worldwide",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs worldwide",
        "remote jobs france"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs europe",
      "normalized": "remote jobs europe",
      "locale": "en",
      "geo": "GB",
      "intent": "jobs",
      "suggestions": [
        "remote jobs europe",
        "remote jobs france"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote software engineer jobs entry level",
      "normalized": "remote software engineer jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 233,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data analyst jobs entry level",
      "normalized": "remote data analyst jobs entry level",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 158,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home",
      "normalized": "work from home",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "part time remote jobs near me",
      "normalized": "part time remote jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "part time remote jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 31,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "emploi",
      "normalized": "emploi",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi télétravail",
        "emploi en ligne",
        "emploi à distance"
      ],
      "searchScore": 13,
      "suggestionCount": 3,
      "sourceQueryCount": 1,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs entry level part time",
      "normalized": "remote jobs entry level part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs entry level near me",
      "normalized": "remote jobs entry level near me",
      "locale": "en",
      "geo": "US",
      "intent": "jobs",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote software engineer jobs reddit",
      "normalized": "remote software engineer jobs reddit",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 6,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 101,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote customer service jobs part time",
      "normalized": "remote customer service jobs part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 5,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 246,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data analyst jobs no experience",
      "normalized": "remote data analyst jobs no experience",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 5,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 158,
      "trendScore": 0,
      "demandScore": 30,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "emploi territorial.fr",
      "normalized": "emploi territorial fr",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi télétravail",
        "emploi en ligne",
        "emploi à distance"
      ],
      "searchScore": 10,
      "suggestionCount": 3,
      "sourceQueryCount": 1,
      "jobMatches": 243,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote marketing jobs",
      "normalized": "remote marketing jobs",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 9,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 85,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote marketing jobs texas",
      "normalized": "remote marketing jobs texas",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 85,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote marketing jobs california",
      "normalized": "remote marketing jobs california",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 85,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote customer service jobs florida",
      "normalized": "remote customer service jobs florida",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 8,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 49,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home part time jobs",
      "normalized": "work from home part time jobs",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs no experience work from home",
      "normalized": "remote jobs no experience work from home",
      "locale": "en",
      "geo": "US",
      "intent": "entry",
      "suggestions": [
        "remote jobs no experience"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 300,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote software engineer jobs usa",
      "normalized": "remote software engineer jobs usa",
      "locale": "en",
      "geo": "US",
      "intent": "development",
      "suggestions": [
        "remote software engineer jobs"
      ],
      "searchScore": 4,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 115,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data analyst jobs part time",
      "normalized": "remote data analyst jobs part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote data analyst jobs"
      ],
      "searchScore": 3,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 158,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote jobs entry level data entry",
      "normalized": "remote jobs entry level data entry",
      "locale": "en",
      "geo": "US",
      "intent": "data",
      "suggestions": [
        "remote jobs entry level"
      ],
      "searchScore": 3,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote data entry jobs part time",
      "normalized": "remote data entry jobs part time",
      "locale": "en",
      "geo": "US",
      "intent": "part-time",
      "suggestions": [
        "remote data entry jobs"
      ],
      "searchScore": 3,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 155,
      "trendScore": 0,
      "demandScore": 29,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "emploi du temps",
      "normalized": "emploi du temps",
      "locale": "fr",
      "geo": "FR",
      "intent": "jobs",
      "suggestions": [
        "emploi télétravail",
        "emploi en ligne",
        "emploi à distance"
      ],
      "searchScore": 9,
      "suggestionCount": 3,
      "sourceQueryCount": 1,
      "jobMatches": 257,
      "trendScore": 0,
      "demandScore": 28,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote marketing jobs near me",
      "normalized": "remote marketing jobs near me",
      "locale": "en",
      "geo": "US",
      "intent": "marketing",
      "suggestions": [
        "remote marketing jobs"
      ],
      "searchScore": 7,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 85,
      "trendScore": 0,
      "demandScore": 28,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "remote customer service jobs california",
      "normalized": "remote customer service jobs california",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "remote customer service jobs"
      ],
      "searchScore": 6,
      "suggestionCount": 3,
      "sourceQueryCount": 3,
      "jobMatches": 49,
      "trendScore": 0,
      "demandScore": 28,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    },
    {
      "keyword": "work from home customer service jobs",
      "normalized": "work from home customer service jobs",
      "locale": "en",
      "geo": "US",
      "intent": "support",
      "suggestions": [
        "work from home jobs"
      ],
      "searchScore": 2,
      "suggestionCount": 2,
      "sourceQueryCount": 2,
      "jobMatches": 246,
      "trendScore": 0,
      "demandScore": 28,
      "demandSignals": [
        "google_autocomplete_ranked",
        "ezyjobs_job_supply"
      ],
      "capturedAt": "2026-10-07T11:05:15.044Z"
    }
  ],
  "inDemandRoles": [
    {
      "title": "Business Development Manager, Product Partnerships",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Software Engineer Intern (2027)",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Director, Growth Sales (AI & Digital Natives) ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Forward Deployed Engineer, Professional Services",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Principal Customer Engineer, Majors",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Senior Account Executive ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Strategic Account Executive - Public Sector ",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Strategic Account Executive",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Senior Software Engineer, Billing Platform",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Director of Product Management, Security",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Principal Product Manager, Security",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Intermediate-Senior Backend Engineer (Ruby), Plan: Spec-Driven Development",
      "count": 2,
      "remoteCount": 2,
      "directCount": 2
    },
    {
      "title": "Developer Marketer - Sales",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Regional Sales Director - France",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Sales Development Representative | Germany | Remote",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Sales Development Representative | Switzerland | Remote",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Engineering Manager, SSCS: Supply Chain",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Sr. Product Marketing Manager",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Senior Named Account Executive,  (MN or WI)",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Workplace Coordinator",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Senior Forward Deployed Engineer",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Director, Global People Operations & Compliance",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Billing Operations Lead",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Software Engineer, Life Sciences",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Head of Story & Communications",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "ITAV Deployment Engineer",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Product Support Engineer - NAMER",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Implementation Consultant - Americas",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Program Manager, Technology Capital Builds",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    },
    {
      "title": "Data Engineer, Core Experimentation",
      "count": 1,
      "remoteCount": 1,
      "directCount": 1
    }
  ],
  "errors": []
} as KeywordDemandSnapshot;
